export const quotes = [
  { text: "Believe in yourself.", author: "Unknown" },
  { text: "Success starts with self-belief.", author: "Unknown" },
  { text: "Dream big and work hard.", author: "Unknown" },
  { text: "Small steps lead to big results.", author: "Unknown" },
  { text: "Your future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Never stop learning.", author: "Unknown" },
  { text: "Stay positive. Work hard. Make it happen.", author: "Unknown" },
  { text: "Do something today your future self will thank you for.", author: "Unknown" },
  { text: "Success is earned, not given.", author: "Unknown" },
  { text: "Progress is better than perfection.", author: "Unknown" },
  { text: "Don't wait for opportunity. Create it.", author: "Unknown" },
  { text: "Be stronger than your excuses.", author: "Unknown" },
  { text: "Consistency beats talent.", author: "Unknown" },
  { text: "Every day is a fresh start.", author: "Unknown" },
  { text: "Failure is a lesson, not the end.", author: "Unknown" },
  { text: "Keep going. You're getting there.", author: "Unknown" },
  { text: "The best time to start is now.", author: "Unknown" },
  { text: "Great things take time.", author: "Unknown" },
  { text: "Focus on progress, not perfection.", author: "Unknown" },
  { text: "Your only limit is your mind.", author: "Unknown" },
  { text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
  { text: "Hard work beats luck.", author: "Unknown" },
  { text: "Learn something new every day.", author: "Unknown" },
  { text: "Difficult roads often lead to beautiful destinations.", author: "Unknown" },
  { text: "Mistakes help you grow.", author: "Unknown" },
  { text: "Nothing changes if nothing changes.", author: "Unknown" },
  { text: "Be the reason someone smiles today.", author: "Unknown" },
  { text: "Success is a journey, not a destination.", author: "Arthur Ashe" },
  { text: "Make today count.", author: "Unknown" },
  { text: "Discipline creates freedom.", author: "Unknown" },
  { text: "Start where you are. Use what you have.", author: "Arthur Ashe" },
  { text: "Action is the key to success.", author: "Pablo Picasso" },
  { text: "Every expert was once a beginner.", author: "Helen Hayes" },
  { text: "Your attitude determines your direction.", author: "Unknown" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Success comes from never giving up.", author: "Unknown" },
  { text: "Think less. Do more.", author: "Unknown" },
  { text: "Good things take time.", author: "Unknown" },
  { text: "Make yourself proud.", author: "Unknown" },
  { text: "Keep moving forward.", author: "Walt Disney" },
  { text: "Every accomplishment starts with a decision to try.", author: "John F. Kennedy" },
  { text: "You are capable of amazing things.", author: "Unknown" },
  { text: "Stay focused and never quit.", author: "Unknown" },
  { text: "Turn your dreams into plans.", author: "Unknown" },
  { text: "Be patient. Great things take time.", author: "Unknown" },
  { text: "Work hard in silence. Let success make the noise.", author: "Frank Ocean" },
  { text: "Your potential is endless.", author: "Unknown" },
  { text: "Be brave enough to start.", author: "Unknown" },
  { text: "Create the life you can't wait to wake up to.", author: "Unknown" },
  { text: "A little progress each day adds up.", author: "Unknown" },
  { text: "Success begins with a single step.", author: "Unknown" },
  { text: "The only way to fail is to quit.", author: "Unknown" },
  { text: "Learn. Improve. Repeat.", author: "Unknown" },
  { text: "Confidence comes from preparation.", author: "Unknown" },
  { text: "Be your own motivation.", author: "Unknown" },
  { text: "One day or day one. You decide.", author: "Unknown" },
  { text: "Keep your goals in sight.", author: "Unknown" },
  { text: "Don't fear failure. Fear regret.", author: "Unknown" },
  { text: "Success is built one day at a time.", author: "Unknown" },
  { text: "The journey is worth it.", author: "Unknown" }
];